### ISSUE TITLE
这个订阅地址无法获取节点信息

### ISSUE THREAD

**Issue by Kevin1996cn** [crazyhl/PullAndMergeConfig#1]
https://raw.githubusercontent.com/ssrsub/ssr/master/Clash.yml
是个公益节点，希望能增加对其支持

**Comment by Kevin1996cn** [comment]
最近一次更新源码之后，获取到的节点只有四个并且名字为1234.

**Comment by crazyhl** [comment]
你说下你是怎么运行的，是不是没有弄配置文件，主要是还没完善，稍后我更新一个使用方法吧

**Comment by crazyhl** [comment]
使用方法已经更新，可以参考使用方法使用

**Comment by Kevin1996cn** [comment]
辛苦辛苦，我刚才又试了一下，应该是我之前操作的问题，现在很好用了。就是有个问题，如何控制fallback组里面节点的先后顺序呢？

**Comment by crazyhl** [comment]
这个目前还控制不了，因为是开了多线程再跑，先后顺序跟哪个获取的快有关，这个可能就得自己手工改一下了。

**Comment by crazyhl** [comment]
我貌似理解错误了，你说的是 dns 里面的 fallback 的顺序么？这个顺序应该是clash 自己的策略，这里面我个人觉得不要配置太多个，否则卡网，用一个就好。个人推荐 `- tls://dns.rubyfish.cn:853` 就够了
