### ISSUE TITLE
mac可执行文件怎么使用？

### ISSUE THREAD

**Issue by Kevin1996cn** [crazyhl/PullAndMergeConfig#2]
不知道该用哪种打开方式。。。
又拍云的作用是保存配置文件吗？然后用这个地址做订阅地址？

**Comment by Kevin1996cn** [comment]
又拍云免费空间申请貌似有点门槛。。。是否有别的替代品？能否传到github?

**Comment by crazyhl** [comment]
可执行文件跟以前差不多啊，配置好配置文件，然后直接双击就可以了，又拍云就是存文件做订阅的，github也可以，找时间我支持一下。

**Comment by Kevin1996cn** [comment]
我双击会自动用文本编辑器打开，应该用哪种方式打开啊？ 我下的只有一个没有扩展名的文件，配置文件是拿之前源码里那个吗？放在可执行文件旁边？

**Comment by crazyhl** [comment]
在命令行下chmod 777 一下，然后命令行运行一下，要不然双击会提示开发者不可信

**Comment by Kevin1996cn** [comment]
ok 解决了，多谢。期待你后续的更新

**Comment by Kevin1996cn** [comment]
对了，可以增加一个输出配置文件到指定路径吗？

**Comment by crazyhl** [comment]
好，可能本周末会支持github的上传
