### ISSUE TITLE
大佬这个问题怎么解决

### ISSUE THREAD

**Issue by yuhualuojin** [crazyhl/PullAndMergeConfig#5]
![image](https://user-images.githubusercontent.com/68735592/173549936-f53732a7-d2a1-475a-bc24-f2372e13538b.png)

**Comment by crazyhl** [comment]
用国内的proxy 服务试试 [https://goproxy.io/zh/](https://goproxy.io/zh/)

**Comment by yuhualuojin** [comment]
![image](https://user-images.githubusercontent.com/68735592/173560459-4533e026-87d2-4425-8399-b7f1af01d07c.png)
![image](https://user-images.githubusercontent.com/68735592/173560545-8897929f-56ae-47bd-85d6-b3326eb6546f.png)

空白的咋办，日志也是空白的

**Comment by yuhualuojin** [comment]
哥哥访问那个网址是空白的咋搞

**Comment by crazyhl** [comment]
其实是有日志的，你可以go build 出来在log 目录下查看日志，或者指定一下运行目录。你的请求url，configName 没有指定，在config 目录下，创建自己的配置文件。所以一定要让程序运行在正确的目录下，这个可以使用 goland 或者其他可以方便指定运行目录的地方去测试运行。如果不方便使用ide，就 go build 出来。在运行

**Comment by yuhualuojin** [comment]
大佬可以了

**Comment by crazyhl** [comment]
ok

**Comment by yuhualuojin** [comment]
![image](https://user-images.githubusercontent.com/68735592/173611912-df0ebbba-f3ec-42f1-916d-53cc4acd6095.png)
大佬这个是啥问题啊，用vmless订阅转换成clash订阅填上的

**Comment by yuhualuojin** [comment]
大佬组怎么添加reject跟direct，合并后全是节点

**Comment by crazyhl** [comment]
reject 和 direct 可以通过 配置文件自行添加，在图片的位置添加，全是节点是什么意思？难道你没拉取到基本配置么？你的那个应该是base64没解析出来，你可以自行修改一下代码，我现在用的是rawurldecoder 和 RawStdEncoding，你可以看下是在哪一步出错了。

<img width="347" alt="image" src="https://user-images.githubusercontent.com/5474833/173743378-8cb46a5a-d940-4bc7-b644-6c2028a0261b.png">

**Comment by yuhualuojin** [comment]
![image](https://user-images.githubusercontent.com/68735592/173748389-8a718965-38b1-492e-b8ce-f4c7e5735fd7.png)
解析失败

**Comment by crazyhl** [comment]
baseName 目前只支持 Hackl0us，另外你的订阅地址直接用原生的，别用转换过的。

**Comment by crazyhl** [comment]
我升级了一个小版本，优化了解析，可以试试了
