### ISSUE TITLE
没学过go语言，不太会操作，main.go已运行 8080端口 

### ISSUE THREAD

**Issue by 14790897** [crazyhl/PullAndMergeConfig#6]
网址：http://127.0.0.1:8080/parse?name=c1
打开空白
没找到错误日志文件

**Comment by 14790897** [comment]
![Snipaste_2023-04-13_14-46-48](https://user-images.githubusercontent.com/121866954/231676566-16a00267-cf80-4477-8d47-c05772c9eaf3.jpg)
![image](https://user-images.githubusercontent.com/121866954/231676621-053db8d2-55b1-470c-bce4-bc6e41538806.png)

**Comment by crazyhl** [comment]
你用的是最新的代码吗？如果是，可以在获取配置文件那边打印一下日志。以及如果方便可以把配置文件贴给我，关键部分自己注释掉即可。
当然你如果仅仅是想解析自己的服务的话，也可以用我提供的网址 [https://parse.cimple.ink/](https://parse.cimple.ink/)
