### ISSUE TITLE
这么好的软件没人维护和使用吗

### ISSUE THREAD

**Issue by windstayNJ** [crazyhl/PullAndMergeConfig#7]
太可惜了，
找不到windows版本

**Comment by crazyhl** [comment]
自己编译一下不就好了吗？

**Comment by windstayNJ** [comment]
> 自己编译一下不就好了吗？

不懂编程不会编译啊

**Comment by crazyhl** [comment]
其实最新的版本，并不是适合在非服务器下使用。如果你仅仅是想单纯的转换合并脚本，可以使用网上公开的服务。或者用我提供的服务 [https://parse.cimple.ink/](https://parse.cimple.ink/)

**Comment by windstayNJ** [comment]
> 其实最新的版本，并不是适合在非服务器下使用。如果你仅仅是想单纯的转换合并脚本，可以使用网上公开的服务。或者用我提供的服务 https://parse.cimple.ink/

谢谢，配置文件有没有类似“自洁"功能，就是不断添加新订阅，配置里可以自动删除无效的节点无效的订阅，这样用户就只管添加就行了。如果没有这个”自洁“功能，越加就会越大，会爆。

**Comment by crazyhl** [comment]
并不会考虑提供此功能，用自动测速即可
