### ISSUE TITLE
【Add】希望能出一个教程

### ISSUE THREAD

**Issue by jiyuxiang01** [crazyhl/PullAndMergeConfig#8]
能出一个使用教程吗？如何运行在window上，非常感谢

**Comment by crazyhl** [comment]
windwos 上是用不了的，目前支持在服务器上。如果你想在 windows 上使用的话，建议使用 v2 分支，可以自行使用 go 编译一下

**Comment by jiyuxiang01** [comment]
> windwos 上是用不了的，目前支持在服务器上。如果你想在 windows 上使用的话，建议使用 v2 分支，可以自行使用 go 编译一下

我现在的需求就是吧机场订阅批量转换为v2格式的节点，目前市面上转换只要选择v2必定排除hy2协议,而我很需要用这个协议，而且我的服务器也是window的

**Comment by crazyhl** [comment]
https://parse.cimple.ink/

用我的开放服务试一下，看看能否满足你的需求，如果也会排除，你可以给我一个例子，我看看支持一下

**Comment by jiyuxiang01** [comment]
> https://parse.cimple.ink/
> 
> 用我的开放服务试一下，看看能否满足你的需求，如果也会排除，你可以给我一个例子，我看看支持一下

好的，能留个邮箱吗？订阅这个东西不方便公开
